---
- name: Deploy ecommerce app
  hosts: web
  become: yes

  tasks:

    # =========================
    # 1. SYSTEM UPDATE
    # =========================
    - name: Update system packages
      dnf:
        name: "*"
        state: latest

    # =========================
    # 2. INSTALL DOCKER
    # =========================
    - name: Install Docker
      dnf:
        name: docker
        state: present

    # =========================
    # 3. START DOCKER SERVICE
    # =========================
    - name: Enable and start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    # =========================
    # 4. ADD EC2 USER TO DOCKER GROUP
    # =========================
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    # =========================
    # 5. ENSURE DOCKER IS READY
    # =========================
    - name: Wait for Docker to be ready
      shell: sleep 10

    # =========================
    # 6. CLEAN OLD CONTAINERS (IMPORTANT)
    # =========================
    - name: Remove existing containers (if any)
      shell: docker rm -f nginx || true

    # =========================
    # 7. RUN APPLICATION
    # =========================
    - name: Run nginx container
      shell: docker run -d --name nginx -p 80:80 nginx