---
- name: Deploy ecommerce app
  hosts: web
  become: yes

  tasks:

    - name: Update system
      dnf:
        name: "*"
        state: latest

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose plugin
      dnf:
        name: docker-compose-plugin
        state: present

    - name: Create app directory
      file:
        path: /app
        state: directory

    - name: Copy app to server
      copy:
        src: ../app/
        dest: /app/

    - name: Run ecommerce app
      shell: |
        cd /app
        docker compose down || true
        docker compose up -d --build