name: Full DevOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    outputs:
      instance_ips: ${{ steps.export.outputs.instance_ips }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Export Instance IPs
        id: export
        run: |
          IPS=$(terraform output -json instance_public_ips | jq -r '.[]' | tr '\n' ',')
          echo "instance_ips=$IPS" >> $GITHUB_OUTPUT